# Server configuration
server:
  host: "localhost"
  port: 8080

# Database configuration and credentials
database:
  host: "postgres"
  port: 5432
  user: "postgres"
  password: "password"
  name: "db_EM"

# Remote server configuration
rmserver:
  protocol: "http"
  host: "192.168.50.245"
  port: 9099
