openapi: 3.1.0
info:
  title: Music library
  version: 0.0.1
paths:
  /song:
    get:
      summary: Request song text
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SongTextRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SongDetail'
        '400':
          description: Bad request
        '404':
          description: Song not found
        '500':
          description: Internal server error
  /library:
    get:
      summary: Request whole library
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LibraryContent'
        '500':
          description: Internal server error
  /rmsong:
    delete:
      summary: Remove song from library
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SongTextRequest'
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad request
        '404':
          description: Song not found
        '500':
          description: Internal server error
  /modsong:
    put:
      summary: Modify song name and group
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SongModRequest'
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad request or item already exists
        '404':
          description: Song not found
        '500':
          description: Internal server error
  /addsong:
    post:
      summary: Add new song
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SongTextRequest'
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad request
        '500':
          description: Internal server error
components:
  schemas:
    SongTextRequest:
      type: object
      properties:
        group:
            type: string
            example: group1
        song:
            type: string
            example: someName
    SongModRequest:
      type: object
      properties:
        group:
          type: string
          example: group1
        song:
          type: string
          example: someName
        new_group:
          type: string
          example: group11
        new_song:
          type: string
          example: someName1
    SongDetail:
      required:
        - song
        - text
      type: object
      properties:
        song:
          type: string
          example: Supermassive Black Hole
        text:
          type: string
          example: Ooh baby, don't you know I suffer?\nOoh baby, can you hear me moan?\nYou caught me under false pretenses\nHow long before you let me go?\n\nOoh\nYou set my soul alight\nOoh\nYou set my soul alight
    LibraryContent:
      type: object
      properties:
        songs:
          type: array
          items:
            $ref: '#/components/schemas/LibraryContentUnit'
    LibraryContentUnit:
      type: object
      properties:
        group:
          type: string
          example: group1
        song:
          type: string
          example: Supermassive Black Hole
        text:
          type: string
          example: Ooh baby, don't you know I suffer?\nOoh baby, can you hear me moan?\nYou caught me under false pretenses\nHow long before you let me go?\n\nOoh\nYou set my soul alight\nOoh\nYou set my soul alight
        release:
          type: string
          example: 2020-10-10
        link:
          type: string
          example: someRealLink
